;;; patchwork-generate-cron-config.el --- regenerate the cron config from your real setup -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;;
;; Regenerates `patchwork-cron-config.el' (the file `patchwork-cron-sync.el'
;; loads for its actual server list -- see its own Commentary) from your
;; REAL interactive configuration, instead of requiring you to hand-copy
;; `patchwork-servers' et al. into a second file and keep the two in sync
;; by hand every time you change one. Run this manually whenever you
;; change your interactive configuration -- NOT from cron itself: unlike
;; `patchwork-cron-sync.el', which deliberately avoids loading your normal
;; init file (slow, assumes a display, package.el network calls, etc.),
;; this script's entire job IS to load it, so paying that cost here is
;; exactly the point; it's a one-off you run by hand, not a five-minute
;; cron tick.
;;
;; Usage:
;;
;;   emacs --batch -l patchwork-generate-cron-config.el -- ~/.emacs.d/init.el
;;
;; Defaults to `user-init-file' (Emacs's own idea of "your init file") if
;; no path is given. Writes to `patchwork-cron-config.el' next to this
;; script, or wherever $PATCHWORK_CRON_CONFIG points -- same variable
;; `patchwork-cron-sync.el' reads its config location from, so pointing
;; both at some other location (e.g. a private dotfiles repo) only needs
;; setting that once.
;;
;; If your real patchwel setup is loaded lazily (e.g. a package manager's
;; `:defer t'), a plain batch load of your init file may never actually
;; trigger it, leaving `patchwork-servers' unbound or empty here even
;; though your interactive session has it configured -- this script warns
;; if that looks like what happened, since the generated file would
;; otherwise silently end up empty.

;;; Code:

(defconst patchwork-generate-cron-config--vars
  '(patchwork-servers
    patchwork-local-db-file
    patchwork-cache-ttl
    patchwork-sync-lookback-days
    patchwork-sync-timeout
    patchwork-detail-fetch-timeout
    patchwork-page-size
    patchwork-user-agent
    patchwork-prune-on-terminal-states
    patchwork-patch-cache-max-age-days)
  "Variables relevant to a headless sync, dumped into the generated
config file when bound after loading the given init file. Deliberately
excludes UI-only settings (highlighting, buffer names, etc.) that don't
affect what a sync actually does.")

;; See patchwork-cron-sync.el's Commentary for why `command-line-args-left'
;; needs handling this way rather than reading it directly: it's the
;; actual mutable queue Emacs's own top-level argument loop keeps popping
;; from once this `-l' script returns, and still contains the literal
;; "--" marker at this point.
(let* ((args (seq-remove (lambda (a) (string= a "--")) command-line-args-left))
       (init-file (expand-file-name
                   (or (car args)
                       (and (boundp 'user-init-file) user-init-file)
                       "~/.emacs.d/init.el")))
       (out-file (or (getenv "PATCHWORK_CRON_CONFIG")
                     (expand-file-name "patchwork-cron-config.el"
                                       (file-name-directory load-file-name)))))
  (setq command-line-args-left nil)
  (unless (file-exists-p init-file)
    (error "patchwork-generate-cron-config: no such init file: %s" init-file))
  (condition-case err
      (load init-file)
    (error
     (message "patchwork-generate-cron-config: warning: %s errored partway through: %s"
              init-file (error-message-string err))
     (message "patchwork-generate-cron-config: continuing with whatever loaded before that")))
  (unless (bound-and-true-p patchwork-servers)
    (message (concat "patchwork-generate-cron-config: warning: patchwork-servers is "
                      "unbound or empty after loading %s -- if patchwel is loaded lazily "
                      "there (e.g. a package manager's `:defer t'), a plain batch load may "
                      "never trigger it; the generated file may end up empty")
             init-file))
  (with-temp-buffer
    (insert (format (concat ";;; %s --- generated by patchwork-generate-cron-config.el, "
                             "do not edit -*- lexical-binding: t; -*-\n")
                     (file-name-nondirectory out-file)))
    (insert (format ";; Generated from %s on %s.\n"
                     init-file (format-time-string "%Y-%m-%dT%H:%M:%SZ" nil t)))
    (insert ";; Re-run patchwork-generate-cron-config.el after changing your\n")
    (insert ";; interactive configuration instead of editing this file directly\n")
    (insert ";; -- it will be overwritten.\n\n")
    (dolist (var patchwork-generate-cron-config--vars)
      (when (boundp var)
        (insert (format "(setq %s '%S)\n" var (symbol-value var)))))
    (write-region (point-min) (point-max) out-file))
  (message "patchwork-generate-cron-config: wrote %s from %s" out-file init-file))

;;; patchwork-generate-cron-config.el ends here
